# Generated by Django 4.2.7 on 2024-05-13 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(db_column='nomeCliente', max_length=50)),
                ('cpf', models.CharField(blank=True, db_column='cpfCliente', max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('excluido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFuncionario', models.CharField(blank=True, max_length=30)),
                ('cpfFuncionario', models.IntegerField(blank=True)),
                ('enderecoFuncionario', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=30)),
                ('sobreNome', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataVenda', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('excluido', models.BooleanField(default=False)),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listagemCliente', to='Tobias.cliente')),
                ('funcionarioId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listagemFuncionario', to='Tobias.funcionario1')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(blank=True, db_column='nomeProduto', max_length=50)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('dataAlteracao', models.DateTimeField(blank=True)),
                ('precoProduto', models.FloatField(blank=True, db_column='precoProduto')),
                ('quantidadeProduto', models.BigIntegerField(blank=True, db_column='quantidadeProduto', default=1)),
                ('status', models.BooleanField(default=True)),
                ('excluido', models.BooleanField(default=False)),
                ('cadastro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='produtoFuncionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produtoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listagemProduto', to='Tobias.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tobias.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tobias.funcionario1')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario1',
            name='autor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cadastro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cadastroFuncionario', to=settings.AUTH_USER_MODEL),
        ),
    ]
