# Generated by Django 4.2.7 on 2024-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='precoItem',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
