# Generated by Django 4.2.7 on 2024-05-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario2',
            old_name='funcionario',
            new_name='funcionarioId',
        ),
    ]
