# Generated by Django 5.0.6 on 2024-06-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estoque',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
