# Generated by Django 4.2.7 on 2024-04-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='precoTotal',
        ),
    ]
