# Generated by Django 4.2.7 on 2024-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Nome_do_produto',
            field=models.CharField(blank=True, db_column='nomeProduto', max_length=50),
        ),
    ]
