# Generated by Django 4.2.7 on 2024-04-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0002_alter_produto_nome_do_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='dataCadastro',
            new_name='dataCad',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Nome_do_produto',
            new_name='nomeProduto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Descricao_do_Produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Numero_de_Nota_Fiscal',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Preco_do_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Quantidade_de_Produtos',
        ),
        migrations.AddField(
            model_name='produto',
            name='precoProduto',
            field=models.FloatField(blank=True, db_column='precoProduto', default=1),
        ),
        migrations.AddField(
            model_name='produto',
            name='qtdProduto',
            field=models.BigIntegerField(blank=True, db_column='quantidadeProduto', default=1),
        ),
    ]
