# Generated by Django 4.2.7 on 2024-04-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0002_remove_venda_precototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='clienteId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='listagemCliente', to='Tobias.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='funcionarioId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='listagemFuncionario', to='Tobias.funcionario1'),
        ),
    ]
