# Generated by Django 4.2.7 on 2024-05-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0002_itemvenda_precoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='precoTotal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
