# Generated by Django 4.2.7 on 2024-04-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nome',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='sobrenome',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='usuario',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
