# Generated by Django 4.2.7 on 2024-05-20 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0002_rename_funcionario_funcionario2_funcionarioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario2',
            name='funcionarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idFuncionario', to=settings.AUTH_USER_MODEL),
        ),
    ]
