# Generated by Django 4.2.7 on 2023-12-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0002_alter_produto_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.TextField(max_length=30),
        ),
    ]
