# Generated by Django 4.2.7 on 2023-12-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0003_alter_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.TextField(),
        ),
    ]
