# Generated by Django 4.2.7 on 2024-04-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0003_rename_nome_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='sobreNome',
        ),
        migrations.AddField(
            model_name='customuser',
            name='endereco',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
