# Generated by Django 4.2.7 on 2024-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0003_alter_venda_clienteid_alter_venda_funcionarioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
