# Generated by Django 4.2.7 on 2024-05-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0003_alter_funcionario2_funcionarioid'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='tot',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='precoTotal',
            field=models.FloatField(default=0),
        ),
    ]
