# Generated by Django 4.2.7 on 2024-04-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0003_rename_datacadastro_produto_datacad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='qtdProduto',
            new_name='quantidadeProduto',
        ),
    ]
