# Generated by Django 4.2.7 on 2024-05-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0004_itemvenda_tot_alter_venda_precototal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='tot',
        ),
    ]
