# Generated by Django 4.2.7 on 2024-04-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0004_rename_qtdproduto_produto_quantidadeproduto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='dataCad',
            new_name='dataCadastro',
        ),
    ]
