# Generated by Django 4.2.7 on 2023-12-15 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0004_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='email',
        ),
        migrations.AddField(
            model_name='produto',
            name='DescProduto',
            field=models.TextField(blank=True, db_column='DescProduto', max_length=1000),
        ),
        migrations.AddField(
            model_name='produto',
            name='NumNotaFiscal',
            field=models.TextField(blank=True, db_column='NumNotaFiscal', max_length=1000),
        ),
        migrations.AddField(
            model_name='produto',
            name='Preco',
            field=models.FloatField(blank=True, db_column='Preco', default=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dataCadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(db_column='nomeProduto', max_length=30),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qtd', models.BigIntegerField(blank=True, db_column='QtdProduto')),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tobias.produto', verbose_name='IdProdutoFK')),
            ],
        ),
    ]
