# Generated by Django 4.2.7 on 2024-04-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0004_alter_venda_excluido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cnpj',
        ),
        migrations.AlterField(
            model_name='venda',
            name='clienteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listagemCliente', to='Tobias.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='funcionarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listagemFuncionario', to='Tobias.funcionario1'),
        ),
    ]
