# Generated by Django 4.2.7 on 2024-04-29 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0005_remove_cliente_cnpj_alter_venda_clienteid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='dataAlteracao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='dataCadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
