# Generated by Django 5.0.6 on 2024-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0005_remove_itemvenda_tot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario1',
            name='cpfFuncionario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
