# Generated by Django 4.2.7 on 2023-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0005_remove_produto_email_produto_descproduto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nomeCliente', max_length=50)),
                ('cpf', models.CharField(blank=True, db_column='cpfCliente', max_length=15)),
                ('cnpj', models.CharField(blank=True, db_column='cnpjCliente', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='QtdProduto',
            field=models.BigIntegerField(blank=True, db_column='Qtd', default=1),
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
