# Generated by Django 4.2.7 on 2024-04-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0005_rename_datacad_produto_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='precoProduto',
            field=models.FloatField(blank=True, db_column='precoProduto'),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precoTotal', models.FloatField()),
                ('produtoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listagem', to='Tobias.produto')),
            ],
        ),
    ]
