# Generated by Django 4.2.7 on 2024-04-16 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0006_alter_linkuser_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='linkuser',
            name='autor',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='autor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkuser',
            name='funcionario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Tobias.funcionario'),
            preserve_default=False,
        ),
    ]
