# Generated by Django 4.2.7 on 2024-04-11 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0006_alter_produto_precoproduto_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFuncionario', models.CharField(blank=True, max_length=30)),
                ('cpfFuncionario', models.IntegerField(blank=True)),
                ('ederecoFuncionario', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='venda',
            name='produtoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listagemProduto', to='Tobias.produto'),
        ),
    ]
