# Generated by Django 5.0.6 on 2024-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0006_remove_funcionario1_cpffuncionario_funcionario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
