# Generated by Django 4.2.7 on 2024-05-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0006_produto_dataalteracao_alter_produto_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='dataVenda',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
