# Generated by Django 4.2.7 on 2024-04-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0007_remove_funcionario_usuario_remove_linkuser_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nome',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='sobreNome',
            new_name='last_name',
        ),
    ]
