# Generated by Django 5.0.6 on 2024-05-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0007_funcionario_excluido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='user_permissions',
        ),
    ]
