# Generated by Django 4.2.7 on 2024-04-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0007_funcionario_alter_venda_produtoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='funcionarioId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='listagemFuncionario', to='Tobias.produto'),
            preserve_default=False,
        ),
    ]
