# Generated by Django 4.2.7 on 2024-04-16 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0008_rename_nome_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='autor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkuser',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tobias.funcionario'),
        ),
    ]
