# Generated by Django 5.0.6 on 2024-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0008_remove_funcionario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
