# Generated by Django 4.2.7 on 2024-03-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0008_customuser_remove_produto_nome_do_produto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
