# Generated by Django 4.2.7 on 2024-04-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0008_venda_funcionarioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='funcionarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listagemFuncionario', to='Tobias.funcionario'),
        ),
    ]
