# Generated by Django 4.2.7 on 2024-04-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0009_alter_venda_funcionarioid'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
