# Generated by Django 4.2.7 on 2024-04-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0010_alter_linkuser_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='sobreNome',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefone',
        ),
    ]
