# Generated by Django 4.2.7 on 2024-04-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0011_cliente_excluido_cliente_status_venda_clienteid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='nomeCliente',
        ),
    ]
