# Generated by Django 4.2.7 on 2024-04-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0012_rename_nome_cliente_nomecliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='ederecoFuncionario',
            new_name='enderecoFuncionario',
        ),
    ]
