# Generated by Django 5.0.6 on 2024-05-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0012_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='Tobias.grupo'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='permissoes',
            field=models.ManyToManyField(blank=True, to='Tobias.permissao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='permissoes',
            field=models.ManyToManyField(blank=True, to='Tobias.permissao'),
        ),
    ]
