# Generated by Django 5.0.6 on 2024-05-31 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0013_grupo_permissao_funcionario_grupos_grupo_permissoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='grupos',
            new_name='groups',
        ),
    ]
