# Generated by Django 5.0.6 on 2024-05-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0015_alter_funcionario_groups'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='permissoes',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
