# Generated by Django 5.0.6 on 2024-06-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0016_alter_funcionario_permissoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Permissao',
        ),
    ]
