# Generated by Django 5.0.6 on 2024-06-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0017_delete_grupo_delete_permissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, db_column='cpfCliente', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='precoItem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produtoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listagemProduto', to='Tobias.produto'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='clienteId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listagemCliente', to='Tobias.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='funcionarioId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listagemFuncionario', to='Tobias.funcionario1'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='precoTotal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
