# Generated by Django 5.0.6 on 2024-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tobias', '0018_alter_cliente_cpf_alter_itemvenda_precoitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
